### ISSUE TITLE
Issue while running `Get-WSAActiveDirectoryGroupDetail`

### ISSUE THREAD

**Issue by Ashwini-Ravi** [vmware/power-validated-solutions-for-cloud-foundation#530]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.1

### Module Version

2.9.0.1029

### PowerShell Version

7.3.6

### PowerCLI Version

13.1.0.21624340

### PowerVCF Version

2.4.1.1000

### Guest Operating System

windows server 2019

### Description

Error while assigning roles to groups in Global wsa.

Get-WSAActiveDirectoryGroupDetail

### Error or Debug Output

PS C:\Windows\System32> $test = (((Get-WSAActiveDirectoryGroupDetail -group $group).Resources.displayName).Split('@')[0] -eq $group)
Get-WSAActiveDirectoryGroupDetail: Cannot bind parameter 'Uri'. Cannot convert value "https:///SAAS/jersey/manager/api/scim/Groups/.search?locale=en" to type "System.Uri". Error: "Invalid URI: The hostname could not be parsed." This failure might be caused by applying the default parameter binding. You can disable the default parameter binding in $PSDefaultParameterValues by setting $PSDefaultParameterValues["Disabled"] to be $true, and retry. The following default parameter was successfully bound for this cmdlet when the error occurred: -SkipCertificateCheck
InvalidOperation: You cannot call a method on a null-valued expression.

### Expected Behavior

Get-WSAActiveDirectoryGroupDetail - should go through without any issues.

### Actual Behavior

Get-WSAActiveDirectoryGroupDetail is failing

### Steps to Reproduce

run the below command in powershell 
(((Get-WSAActiveDirectoryGroupDetail -group $group).Resources.displayName).Split('@')[0] -eq $group)

**Comment by GaryJBlake** [comment]
Addressed with commit: https://github.com/vmware/power-validated-solutions-for-cloud-foundation/pull/540

This issue was not a bug as such, the platform where the function was being executed had a missing global group in active directory being passed so a PRE_VALIDATION_FAILED error was being generated however within the `Invoke-GlobalWsaAccess` end-to-end deployment the error was not being displayed correctly due to the older message capture process being used.

`Invoke-GlobalWsaAccess` has been updated to use `messageHandler` function now which displays the output more efficiently.
